name: Weight Off
favicon: null
layout_spectrum: 0.21495758183300495
typography_spectrum: 0.03548075957223773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.375
  lightness: 0.9285437557846308
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
